#!/usr/bin/env sh

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# More Aliases
alias cls='clear'
alias h='history'
alias j='jobs -l'

# show open ports
alias ports='ss -tulanp'

# Resume wget by default
alias wget='wget -c'
alias df='df -H'
alias du='du -ch'
# alias rm='rm -i'
alias free='free -m'                      # show sizes in MB

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# System Aliases
alias hogs='ps uxga | sort --key=3.1 -n | head -n 10'
# Run last command with sudo
alias please='sudo $(fc -ln -1)'
alias pls='please'

# Ubuntu Specific
alias sau='sudo apt update'
alias sag='sudo apt upgrade'
alias sai='sudo apt install'

# if exa exists use exa
if command -v exa &> /dev/null
then
    alias ls='exa --icons --color=always --group-directories-first' # my preferred listing
    alias la='exa -a --icons --color=always --group-directories-first'  # all files and dirs
    alias ll='exa -al --icons --color=always --group-directories-first'  # long format
    alias lt='exa -aT --icons --color=always --group-directories-first' # tree listing
    alias l.='la -d .*'

fi

if command -v exa &> /dev/null
then
    alias cat='bat'
fi

# cd ladder
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."